"use client";

import { useRef } from "react";
import { motion, useInView } from "framer-motion";

const ACTIVES = [
  {
    amount: "750",
    unit: "mg",
    name: "Magnesium Bisglycinate",
    product: "Magnesium Max",
    color: "#74B3CE",
    colorDark: "#004346",
    colorBg: "#D6F3F4",
    benefits: ["Most absorbable magnesium form", "Crosses the blood-brain barrier"],
    why: "Bound to glycine, an amino acid with its own calming properties. Your cells absorb this form 3-4x better than oxide.",
  },
  {
    amount: "500",
    unit: "mg",
    name: "L-Glutathione",
    product: "Grenee",
    color: "#9E6899",
    colorDark: "#5B3765",
    colorBg: "#F3CCDE",
    benefits: ["Body's master antioxidant", "Regenerated by Alpha Lipoic Acid"],
    why: "Produced naturally in every cell, but depleted by stress, pollution, and time. This dose is what clinical protocols use.",
  },
  {
    amount: "100K",
    unit: "IU",
    name: "Vitamin D3 + K2 (MK7)",
    product: "DAOS-D",
    color: "#508991",
    colorDark: "#172A3A",
    colorBg: "#D6F3F4",
    benefits: ["K2 directs calcium to bone, not arteries", "MK-7: longest-acting K2 form"],
    why: "D3 without K2 leaves calcium direction to chance. MK-7 has a 3-day half-life, meaning one dose keeps working through the week.",
  },
];

function CountUp({ value, unit }) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-60px" });

  return (
    <div ref={ref} style={{ display: "flex", alignItems: "baseline", gap: 4 }}>
      <span
        style={{
          fontFamily: "var(--font-display)",
          fontSize: "clamp(40px, 6vw, 64px)",
          fontWeight: 400,
          lineHeight: 1,
          transition: "opacity 0.5s ease",
          opacity: isInView ? 1 : 0,
        }}
      >
        {value}
      </span>
      <span
        style={{
          fontFamily: "var(--font-mono)",
          fontSize: "clamp(14px, 2vw, 18px)",
          fontWeight: 400,
          opacity: isInView ? 0.7 : 0,
          transition: "opacity 0.5s ease 0.3s",
        }}
      >
        {unit}
      </span>
    </div>
  );
}

export default function IngredientSpotlight() {
  return (
    <section
      style={{
        padding: "var(--section-py) 0",
        background: "var(--bg-surface)",
      }}
    >
      <div
        style={{
          maxWidth: 1280,
          marginInline: "auto",
          paddingInline: "var(--container-px)",
        }}
      >
        {/* Heading */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.85 }}
          style={{ textAlign: "center", marginBottom: 64 }}
        >
          <p
            style={{
              fontFamily: "var(--font-mono)",
              fontSize: 10,
              letterSpacing: "0.28em",
              textTransform: "uppercase",
              color: "var(--mid)",
              marginBottom: 16,
            }}
          >
            Active Ingredients
          </p>
          <h2
            style={{
              fontFamily: "var(--font-display)",
              fontSize: "var(--text-h2)",
              fontWeight: 400,
              color: "var(--text-primary)",
              letterSpacing: "-0.02em",
            }}
          >
            The dose that{" "}
            <em style={{ fontStyle: "italic", color: "var(--mid)" }}>actually works</em>
          </h2>
        </motion.div>

        {/* Ingredient cards */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
            gap: 24,
          }}
          className="ingredient-grid"
        >
          {ACTIVES.map((active, i) => (
            <motion.div
              key={active.name}
              initial={{ opacity: 0, y: 36 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-40px" }}
              transition={{ delay: i * 0.12, duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
            >
              <IngredientCard active={active} />
            </motion.div>
          ))}
        </div>
      </div>

      <style>{`
        @media (max-width: 768px) {
          .ingredient-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </section>
  );
}

function IngredientCard({ active }) {
  return (
    <div
      style={{
        background: "var(--bg-surface)",
        border: "1px solid var(--border-subtle)",
        borderRadius: "var(--radius-card)",
        overflow: "hidden",
        boxShadow: "var(--shadow-card)",
        transition: "box-shadow 0.3s ease, transform 0.3s ease",
        height: "100%",
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.boxShadow = "var(--shadow-hover)";
        e.currentTarget.style.transform = "translateY(-4px)";
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.boxShadow = "var(--shadow-card)";
        e.currentTarget.style.transform = "translateY(0)";
      }}
    >
      {/* Colored top band */}
      <div
        style={{
          height: 6,
          background: `linear-gradient(90deg, ${active.colorDark}, ${active.color})`,
        }}
      />

      <div style={{ padding: "28px 28px 32px" }}>
        {/* Amount */}
        <div style={{ color: active.colorDark, marginBottom: 8 }}>
          <CountUp value={active.amount} unit={active.unit} />
        </div>

        {/* Name */}
        <h3
          style={{
            fontFamily: "var(--font-display)",
            fontSize: "clamp(16px, 2vw, 19px)",
            fontWeight: 500,
            color: "var(--text-primary)",
            marginBottom: 4,
            lineHeight: 1.3,
          }}
        >
          {active.name}
        </h3>
        <p
          style={{
            fontFamily: "var(--font-mono)",
            fontSize: 10,
            letterSpacing: "0.14em",
            textTransform: "uppercase",
            color: active.color,
            marginBottom: 20,
          }}
        >
          in {active.product}
        </p>

        {/* Why */}
        <p
          style={{
            fontFamily: "var(--font-body)",
            fontSize: 13,
            color: "var(--text-secondary)",
            lineHeight: 1.75,
            marginBottom: 20,
            paddingBottom: 20,
            borderBottom: "1px solid var(--border-subtle)",
          }}
        >
          {active.why}
        </p>

        {/* Benefit bullets */}
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {active.benefits.map((b) => (
            <div key={b} style={{ display: "flex", alignItems: "flex-start", gap: 10 }}>
              <div
                style={{
                  width: 18,
                  height: 18,
                  borderRadius: "50%",
                  background: `${active.colorBg}`,
                  border: `1px solid ${active.color}30`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  flexShrink: 0,
                  marginTop: 1,
                }}
              >
                <svg width={9} height={9} viewBox="0 0 12 12" fill="none">
                  <path d="M2 6l3 3 5-5" stroke={active.colorDark} strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              </div>
              <span
                style={{
                  fontFamily: "var(--font-body)",
                  fontSize: 12,
                  color: "var(--text-secondary)",
                  lineHeight: 1.5,
                }}
              >
                {b}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
